name: Capstone Project Platform - Gcp Deployment
on: push


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: First step of Deployment
        run: echo "Starting GCP Deployment Process"

      - name: Second step of Deployment
        run: echo "Finalizing the GCP Deployment Process "
